### ISSUE TITLE
Failing Test - AreaAndPositionTest#test2

### ISSUE THREAD

**Issue by snodnipper** [alexvoronov/geonetworking#48]
I am getting inconsistent results with the following code between the JVM and Android.

```java
@Test
public void test2() {
   EqualsVerifier.forClass(Area.class).verify();
}
```

I believe the root cause of the problem is because the Area equality check casts a double to a short and the EqualsVerifier test library has no knowledge of such behaviour.

With the JVM, I appear to get test values such as 

```
reference: Area [center=Pos(0.5, 0.5), distanceAmeters=0.5, distanceBmeters=0.5, angleDegreesFromNorth=0.5, type=CIRCLE]
```

```
changed: Area [center=Pos(0.5, 0.5), distanceAmeters=1.0, distanceBmeters=0.5, angleDegreesFromNorth=0.5, type=CIRCLE]
```
which I have been debugging at line 167 in the 1.7.2 library.  For a quick glance, a link to the [current code](https://github.com/jqno/equalsverifier/blob/7543316fc54e11361e599c57b284a0f9beed5fd4/src/main/java/nl/jqno/equalsverifier/internal/checkers/FieldsChecker.java#L173).

You will note that the [short cast](https://github.com/alexvoronov/geonetworking/blob/57a43113aeabc25f005ea17f76409aed148e67b5/geonetworking/src/main/java/net/gcdc/geonetworking/Area.java#L59) make the distanceAmeters different (0 vs 1) _but_ in the Android implementation I get test values:

```
reference: Area [center=null, distanceAmeters=0.0, distanceBmeters=0.0, angleDegreesFromNorth=0.0, type=null]
```

```
changed: Area [center=null, distanceAmeters=0.5, distanceBmeters=0.0, angleDegreesFromNorth=0.0, type=null]
```

where clearly 0 and 0.5 round down to 0 vs 0, which is a different result the JVM values of 0 vs 1.

Perhaps we can adjust the test or make the equality more robust given the input - e.g. int param at mm resolution....although I am not aware of any specification specifics.

Any thoughts / suggestions would be appreciated - thanks!

**Comment by alexvoronov** [comment]
Thanks for the report! 

Area in ETSI standard is encoded as `short`, but I chose to use `double` in the implementation (now I don't even remember why, maybe for consistency or convenience). However, I decided that equality should use precision of the ETSI standard, and consider "more" things equal to each other.

If I understood correctly, there is a difference in how rounding is done during the `short` cast between JVM and Android. One solution would be to add explicit rounding before the cast - it will have some overhead, but I don't think `Area` equality is called that often.

**Comment by snodnipper** [comment]
Sorry, there is no issue with rounding.  It is just that Android and the JVM pick different random values (assuming somewhere in equality lib they are using random for the test values).

It is simply that picking random values 0 and 0.5...and then 0.5 and 1 yields different results when casting (rounding down).  0 and 0.5 round down to 0.  0.5 and 1 round down to 0 and 1.  Test4 is therefore unpredictable.  The android tools picked the first random values and the JVM picked the second random values.

Happy to help as necessary but perhaps the constructor can just use a short (as per spec)...and we have a convenience method (maybe constructor) to convert from double to short.  The builder pattern is common.  We'd therefore change the test to work with short values - and not test the double behaviour in test4.

**Comment by snodnipper** [comment]
Ah, I see what has happened.  nl.jqno.equalsverifier:equalsverifier:2.5.2 seems to have different behaviour, which is what I was using with the Android build.

I got the following from your project:

<img width="980" alt="screen shot 2018-09-01 at 13 42 39" src="https://user-images.githubusercontent.com/576719/44946080-fa6af200-adec-11e8-8094-aee44bbc53c8.png">

**Comment by snodnipper** [comment]
A colleague passed the following reference to me with reference to vehicles:

<img width="666" alt="screen shot 2018-09-03 at 14 19 40" src="https://user-images.githubusercontent.com/576719/44989028-751a4580-af84-11e8-9bf4-e79ef245dbe6.png">

Source: [https://www.etsi.org/deliver/etsi_ts/102800_102899/10289402/01.03.01_60/ts_10289402v010301p.pdf](https://www.etsi.org/deliver/etsi_ts/102800_102899/10289402/01.03.01_60/ts_10289402v010301p.pdf) (page 66).

With reference to [Area](https://www.etsi.org/deliver/etsi_en/302900_302999/302931/01.01.01_60/en_302931v010101p.pdf), what strikes me is:
(1) lack of measurement unit suggests that Area is generic/abstract
(2) the area definition could therefore be applied to many contexts

Clearly, we are interested in vehicle Cooperative Awareness Messages (CAMs), where the length (as defined in the reference above) is defined in decimetres (10 centimetre resolution), which is different to your definition in meters.

I guess we could consider your area as a CamArea (or abstract the measurement unit, e.g. mm/cm/m, as a Java class).

Given that a Java short meets the CAM storage requirement, we could store as a decimetre integer (short value) and, if desirable, create a double convenience constructer / method defined in metres but rounded to decimetres.  That would ensure that the equality contract is sound.

I have no strong preference but I'd be keen to hear your thoughts.

I am happy to make a PR if that would help.

**Comment by alexvoronov** [comment]
Here is a better reference to the standard: [ETSI EN 302 636-4-1](https://www.etsi.org/deliver/etsi_en/302600_302699/3026360401/01.03.01_60/en_3026360401v010301p.pdf), page 31. There it says: "Distance a; 16-bit unsigned integer; Distance a of the geometric shape ..., in metres." So decimeters can be skipped.

I want to believe that current `equals` fullfills [The Contract](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)). It will return true for `a==b` if `a=0.1` and `b=0.7`, it will return it consistently, and it will return true for `b==a` etc. 

Now I remember the reason for using `double`. There is no `unsigned short` in Java, only `short`. So all arithmetic would be messed up. Maybe "upgrading" to `int` would have been a better option, but I went all the way to `double`, in hope that it will be easier to implement characteristic function for areas, and to be consistent with [net/gcdc/geonetworking/Position.java](https://github.com/alexvoronov/geonetworking/blob/57a43113aeabc25f005ea17f76409aed148e67b5/geonetworking/src/main/java/net/gcdc/geonetworking/Position.java#L22). It is strange that the test does not fail for Position equality check.

I think it is easier to ignore the offending test for now :)

By the way, since you are running on Android, how did you work around #47 ? And how do you send the messages, which network card and which drivers? I'm just curious.

**Comment by snodnipper** [comment]
Sorry for the delay and thanks for commenting.

> Here is a better reference to the standard: ETSI EN 302 636-4-1, page 31. There it says: "Distance a; 16-bit unsigned integer; Distance a of the geometric shape ..., in metres." So decimeters can be skipped.

👍

> I want to believe that current equals fullfills The Contract. It will return true for a==b if a=0.1 and b=0.7, it will return it consistently, and it will return true for b==a etc.

In principle, double/float equality does not support a == b reliably, which is why deltas/epsilons are used for floating-point comparison.  Integers are a different category of number and do allow reliable comparison.

The short cast made the comparison integer based, which was consistent.  That said, my interpretation was that the object set out to represent Area that could be written to bytes and restored.  As such, if folks use a double then a value _A_ might go in and essentially _A'_ would come back as slightly different when deserialised.  I haven't considered the impact of that behaviour in `#f`
_Separately, I noticed the Type attribute was not serialised to bytes, which currently doesn't allow objects to be restored reliably if anything other than a rectangle - consistent with your GBC/GAC packet header reference._

> By the way, since you are running on Android, how did you work around #47 ?

With respect to https://github.com/alexvoronov/geonetworking/issues/47, without studying that code in detail, it would appear that the use of `#getDeclaredFields` does not adhere to the Java specification, which [states](https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getDeclaredFields()) `[t]he elements in the array returned are not sorted and are not in any particular order.` This might be likened to JSON, where maps are not ordered - fyi [SO comments / reference](https://stackoverflow.com/questions/4515676/keep-the-order-of-the-json-keys-during-json-conversion-to-csv#answer-4515863).

I will need to get this working for Android and I'll have a look at that now.

> And how do you send the messages, which network card and which drivers? I'm just curious.

**Comment by snodnipper** [comment]
I sympathise with the https://github.com/alexvoronov/geonetworking/issues/47 situation.  I am not familiar with the ETSI specs myself _but_ Java tends to favour the explicit definition of messages, which in this instance could cause a lot of boilerplate.  In Android, we use a generic ContentValues structure quite a bit, which is a `key -> value` structure but I certainly cannot suggest right now we rewrite those classes to use that structure.  I'll mull over some options this weekend.  Cheers!

**Comment by alexvoronov** [comment]
Regarding #47, I deliberately ignored what Java spec says, since my implementation (JDK) returned fields in the declaration order, and it greatly simplified the implementation. The "good news" is that you can switch this ASN.1 implementation to any other Android-compatible ASN.1 implementation. There are at least four commercial ASN.1 Java implementations that you can try (OSS Nokalva, Objective Systems, Marben, Unigone).

The best would be to implement codegen that would produce code that would not rely on the Java fields order (and skip reflection altogether), but that's quite an undertaking and is outside of my scope, and that's what commercial implementations already provide.

**Comment by snodnipper** [comment]
Thank you for your suggestions - much appreciated and I'll give it some thought.  I was considering [JavaPoet](https://github.com/square/javapoet) earlier.

I'll close this issue as https://github.com/alexvoronov/geonetworking/pull/51/ resolves it.  Thanks.  Have a great weekend!
