### ISSUE TITLE
Starting uppertester

### ISSUE THREAD

**Issue by lucar91** [alexvoronov/geonetworking#54]
Hi, I would like to test the v2x with 2 computers. I have already set up access with 802.11p protocol and OCB mode. 

1)First device

I started by starting udp2eth and the result is:
Device name: wlp3s0 (my device)
Promiscuous: no
Serv Addr:  0.0.0.0:1235
Client Addr: 127.0.0.1:1236
open_eth_socket: unumble to create socket.

Then start:
mvn --projects uppertester exec: java -Dexec.mainClass = "net.gcdc.uppertester.ItsStation" -Dexec.args = "- localPortForUdpLinkLayer 1236 --remoteAddressForUdpLinkLayer 127.0.0.1:1235 --upperTesterUdpPort 1600 --hasEthernetHeader".

2)second device
Creating the network and starting udp2eth also in the second device, should it be enough to receive the cam packages?

Which address should I enter in the mvn command instead of 127.0.0.1, the others are correct? (Client and server address)

Sorry, I'm new in this environment...

**Comment by severinson** [comment]
Hi. I'd recommend having a look at the Rendits routing app (fill disclosure: it's written by me). It may be easier to start there than to use this library on its own. More info on how to set it up is available in the manual: https://github.com/rendits/router/raw/master/doc/manual.pdf

**Comment by lucar91** [comment]
Thanks for the quick answer. I'm trying now.

**Comment by alexvoronov** [comment]
It's a lot of things that have to be "wired" to each other, especially since Java can't access raw sockets directly. Beside Rendits, there are some more examples in the README: https://github.com/alexvoronov/geonetworking/blob/master/geonetworking/README.md

Just some background: to get network traffic out of Java and to the network, the library uses an interface [LinkLayer](https://github.com/alexvoronov/geonetworking/blob/master/geonetworking/src/main/java/net/gcdc/geonetworking/LinkLayer.java). You can implement it in any way you like. The easiest for me was to implement it by sending data via UDP to "something outside", and receiving it back the same way. Now, there are two implementations of "something outside": [udp2eth](https://github.com/jandejongh/udp2eth) (single executable) and [utoepy](https://github.com/alexvoronov/utoepy) (a pair of udp2eth.py and eth2udp.py).

Back to you problem: start by making sure that udp2eth has started properly on both computers. Send some udp message to udp2eth on one computer and see if you receive it on udp from udp2eth on another computer. You can send and receive UDP messages with something like netcat (nc).

Your settings seem to be correct, and should be enough. You can use the same on your second machine too.

**Comment by lucar91** [comment]
Hello, thanks for the reply. Sorry if I answer only now but I tried to set everything, now I have also fixed JDK and JRE and I no longer have an error when I start "mvn clean install" (already I had "success" for all and a "failure" with uppertester).

I tried, as you said, to send a packet to the second machine and with wireshark I detect the packet (1 byte). Then I made the configuration that I wrote in the first post and I replaced the address with my (127.0.0.1 -> 192.168.1.3). Wirshark detects UDP packets (90 bytes).
Now I'm checking if the content is correct. In the "data" field the content should be the message CAM (or other messages), right?

**Comment by alexvoronov** [comment]
If you are sending CAM messages, yes, it should contain CAM, BTP header, and GeoNetworking header. To see that in Wireshark you'd need CAM, BTP and GN dissectors.

**Comment by lucar91** [comment]
Hello, sorry I solved it now otherwise I would have deleted the last message. I solved in my case by modifying in the itsStation class:
 
private void onCamReceived(byte[] cam) {
       Cam c = new Cam();
        Cam result = UperEncoder.decode(cam,c.getClass());
        logger.info("----------------Content: ------------");
        logger.info("" + result);
        logger.info("----------------END---------------");
    }

and in this way I can read all the contents of the CAM message.

Thank you so much again for the help also to @severinson

**Comment by alexvoronov** [comment]
Thanks for sharing your solution with us! Glad you found what you were looking for :)
